apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-test
  template:
    metadata:
      labels:
        app: mini-test
    spec:
      containers:
      - name: mini-test-container
        image: mini-test:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mini-test-service
spec:
  selector:
    app: mini-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
